### PR TITLE
Fix async to dispatch to the correct locality in all cases

### LINKED ISSUE #1813: async(launch::..., action(), ...) always invokes locally
Invocations of async() with an action supplying a launch policy are dispatched erroneously to one of the local overloads for async. The test case below demonstrates the issue:

```
#include <hpx/hpx_init.hpp>
#include <hpx/include/async.hpp>
#include <hpx/util/lightweight_test.hpp>

///////////////////////////////////////////////////////////////////////////////
hpx::id_type get_locality()
{
    return hpx::find_here();
}
HPX_PLAIN_ACTION(get_locality);

void test_remote_async(hpx::id_type target)
{
    get_locality_action act;
    hpx::future<hpx::id_type> f2 = hpx::async(hpx::launch::all, act, target);
    HPX_TEST_EQ(f2.get(), target);
}

int hpx_main()
{
    std::vector<hpx::id_type> localities = hpx::find_all_localities();
    for (hpx::id_type const& id : localities)
    {
        test_remote_async(id);
    }
    return hpx::finalize();
}

int main(int argc, char* argv[])
{
    // Initialize and run HPX
    HPX_TEST_EQ_MSG(hpx::init(argc, argv), 0,
        "HPX main exited with non-zero status");

    return hpx::util::report_errors();
}
```

### PR DESCRIPTION
**Pull request by hkaiser**
- This fixes #1813: async(launch::..., action(), ...) always invokes locally

### CODE REVIEW

File: hpx/lcos/async.hpp [hunk 1]
```diff
@@ -158,43 +193,23 @@ namespace hpx { namespace detail
         }
     };
 
-    ///////////////////////////////////////////////////////////////////////////
+    // BOOST_SCOPED_ENUM(launch)
     template <typename Policy>
     struct async_dispatch<Policy,
```
Comment (sithhell) [inline hpx/lcos/async.hpp]: Shouldn't this go into hpx/async.hpp instead?

Comment (hkaiser) [inline hpx/lcos/async.hpp]: This is the implementation of `async(launch::..., F, ...)`, i.e. for the local case. The remote case is implemented in `hpx/async.hpp`

Comment (sithhell) [inline hpx/lcos/async.hpp]: The local case should be implemented in `hpx/async.hpp` and the remote in `hpx/lcos/async.hpp`, right? This seems to be the case already, the only thing I am wondering is if the implementation of `async_dispatch` shouldn't go into `hpx/async.hpp` instead, as it is the case for all others. In the, it shouldn't really matter. `hpx/lcos/async.hpp` is included by `hpx/async.hpp` anyways. I was thinking about the corner case where you only want to include the local async variants, which seems to be impossible at the moment anyways.

Comment (hkaiser) [inline hpx/lcos/async.hpp]: The file `hpx/lcos/async.hpp` is included by `hpx/async.hpp`. If we move this definition to `hpx/async.hpp` it will not be available for the stuff needed in `hpx/lcos/async.hpp`.

**Comment by sithhell** [comment]
LGTM. Does this also fix #1523?

**Comment by hkaiser** [comment]
> Does this also fix #1523?

No, it does not do anything to fix #1523. This has to be addressed separately.
