### PR TITLE
Changing return type of hardware_concurrency() to unsigned int

### LINKED ISSUE #4569: Annoying warning when compiling - pls suppress or fix it.
## Expected Behavior

no warning

## Actual Behavior

getting the following warning over and over again:
....  include\hpx\threading\jthread.hpp(258): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data 

## Steps to Reproduce the Problem

compile with MSVC, enabling jemalloc

## Specifications

  - HPX Version: stable : c5b1812e0d414c33a9068d101075e2aab9afeb6d
  - Windows 10, MSVC latest 2019

### PR DESCRIPTION
**Pull request by hkaiser**
Fixes #4569

- flyby: making the return value `[[nodiscard]]`

### CODE REVIEW

**Comment by McKillroy** [comment]
Works for me - the warnings are gone.

File: libs/topology/src/topology.cpp [hunk 1]
```diff
@@ -1521,9 +1521,9 @@ namespace hpx { namespace threads {
         std::size_t num_of_cores_;
     };
 
-    std::size_t hardware_concurrency()
+    unsigned int hardware_concurrency()
     {
         util::static_<hw_concurrency, hardware_concurrency_tag> hwc;
-        return hwc.get().num_of_cores_;
+        return static_cast<std::size_t>(hwc.get().num_of_cores_);
```
Comment (aurianer) [inline libs/topology/src/topology.cpp:1527]: Is this supposed to be a cast into `std::size_t` ?

Comment (hkaiser) [reply libs/topology/src/topology.cpp:1527]: Most likely not (even if it does no harm)! Thanks for noticing!

Comment (hkaiser) [reply libs/topology/src/topology.cpp:1527]: See #4583 for a fix.
