### PR TITLE
Fix a strange thing in parallel::detail::handle_exception. (Fix #2834.)

### LINKED ISSUE #2834: One suspicion in parallel::detail::handle_exception.
I have one doubt about parallel::detail::handle_exception.
https://github.com/STEllAR-GROUP/hpx/blob/76f7c3bc8eac51d73be7de4146b729335ce03c3f/hpx/parallel/exception_list.hpp#L26-L74
Above, the first ```handle_exception_impl<>::call()``` in Line 31 just throws exception. But, the second and third one return an exceptional future. As I think, this is strange. It seems inconsistent.

I think that the struct of Line 79 is for parallel algorithm called with ```execution::task```. So, in the struct, ```call()``` all both should return ```hpx::future<Result>```. (In other words, should return exceptional future.)
But in case of Line 27, it is different case. So, it should just return ```Result``` as I think. (In other words, should just throw exception.)

How do you think about this issue?

### LINKED ISSUE #3088: A strange thing in parallel::sort.
https://github.com/STEllAR-GROUP/hpx/blob/f63f4b953917386f28fff31c0fde8ce61634247e/hpx/parallel/algorithms/sort.hpp#L210-L214

```result```(hpx::future) is returned from ```execution::async_execute()```. So, if the task is running, ```result.has_exception()``` always returns ```false```.

As I think, that code block(L210-L214) is not necessary because anyhow the exception which is occurred in the task is wrapped into the future(```result```).

### PR DESCRIPTION
**Pull request by taeguk**
Fixes #2834 .
flyby: Fixes #3088 .

### CODE REVIEW

**Comment by hkaiser** [comment]
@taeguk Thanks for looking into this! It's overdue that you get access to the repository - I've sent you an invite.

File: hpx/parallel/algorithms/sort.hpp [hunk 1]
```diff
@@ -201,19 +202,22 @@ namespace hpx { namespace parallel { inline namespace v1
                 result = execution::async_execute(policy.executor(),
                         &sort_thread<ExPolicy, RandomIt, Compare>,
                         std::ref(policy), first, last, comp);
+
+                return result;
```
Comment (hkaiser) [inline hpx/parallel/algorithms/sort.hpp]: Wouldn't a simple

    return execution::async_execute(policy.executor(),  
        &sort_thread<ExPolicy, RandomIt, Compare>,  
        std::ref(policy), first, last, comp);

do the trick here?

File: hpx/parallel/algorithms/sort.hpp [hunk 2]
```diff
@@ -201,19 +202,22 @@ namespace hpx { namespace parallel { inline namespace v1
...
-            {
-                return detail::handle_exception<ExPolicy, RandomIt>::call(
-                    std::move(result));
+                    // Not reachable.
+                    HPX_ASSERT(false);
+                }
+                catch (...) {
+                    return hpx::make_exceptional_future<RandomIt>(
+                        std::current_exception());
+                }
```
Comment (hkaiser) [inline hpx/parallel/algorithms/sort.hpp]: Hmmm, do we really have to use nested try/catch blocks here? `handle_local_exceptions` only rethrows the current exception as an exception list. Couldn't we directly call `make_exceptional_future` with a exception list constructed from the current exception?

File: hpx/parallel/algorithms/sort.hpp (hunk 1 above)
Comment (taeguk) [reply hpx/parallel/algorithms/sort.hpp]: @hkaiser You're right. That code was derived from just moving ```return result;``` into inside of try block. I'll fix that like you said.

File: hpx/parallel/exception_list.hpp [hunk 3]
```diff
@@ -87,11 +81,11 @@ namespace hpx { namespace parallel { inline namespace v1
...
+                    catch(std::bad_alloc const&) {
+                        throw;
                     }
-                    catch (hpx::exception_list const& el) {
-                        throw el;
+                    catch (hpx::exception_list const&) {
+                        throw;
                     }
                     catch (...) {
                         throw hpx::exception_list(std::current_exception());
```
Comment (hkaiser) [inline hpx/parallel/exception_list.hpp]: Hmm, this looks really strange (it probably was strange all along). I'm sure this can be done with one level of try/catch blocks.

File: hpx/parallel/algorithms/sort.hpp (hunk 2 above)
Comment (taeguk) [reply hpx/parallel/algorithms/sort.hpp]: @hkaiser ```handle_local_exceptions()`` handles an exception differently when ```std::current_exception()``` means ```std::bad_alloc```. In that case, ```handle_local_exceptions()``` just rethrows ```std::bad_alloc``` without wrapping into ```exception_list```.
We need to handle the exception differently according to what is the exception which we handles. And for that, I used ```handle_local_exception()```.
And nested catch (Line216-219) is needed for wrapping an exception which is threw properly from ```handle_local_exception()```.

Comment (hkaiser) [reply hpx/parallel/algorithms/sort.hpp]: @taeguk yes, I understand. Still, there might be a better way.

File: hpx/parallel/exception_list.hpp (hunk 3 above)
Comment (taeguk) [reply hpx/parallel/exception_list.hpp]: @hkaiser Yes, we can do that with only one level of try/catch blocks.

File: hpx/parallel/algorithms/sort.hpp (hunk 2 above)
Comment (taeguk) [reply hpx/parallel/algorithms/sort.hpp]: @hkaiser Aha, okay i got it.
https://github.com/taeguk/hpx/blob/9d72e4de54495987597bc2e6bbe609bc8125a01c/hpx/parallel/algorithms/sort.hpp#L249-L260
If we move that exception handling from Line208 to above lines, we can avoid nested try/catch blocks with just calling ```detail::handle_exception()```.

Comment (taeguk) [reply hpx/parallel/algorithms/sort.hpp]: For example, https://github.com/taeguk/hpx/blob/9d72e4de54495987597bc2e6bbe609bc8125a01c/hpx/parallel/algorithms/partition.hpp#L963-L975
