### PR TITLE
Only use sched_getcpu on linux machines

### LINKED ISSUE #2862: sched_getcpu not available on MacOS
On MacOS `hpx/examples/resource_partitioner/simple_resource_partitioner.cpp` fails to compile on the current master because `hpx/examples/resource_partitioner/shared_priority_scheduler.hpp` includes `parcelport_logging.hpp` which uses the `sched_getcpu` system call which is not part of `sched.h` on MacOS. This include is currently protected by a `#if !defined(HPX_MSVC)` which should probably be expanded to check for MacOS as well or else implemented in a more portable way. The `sched_getcpu` call was added in ecb798fff31c0aa729626f0bbc6281dfa4683a8b.

### PR DESCRIPTION
**Pull request by biddisco**
This Fixes #2862

### CODE REVIEW

File: plugins/parcelport/parcelport_logging.hpp [hunk 1]
```diff
@@ -19,7 +19,12 @@
 #include <hpx/util/detail/pp/stringize.hpp>
 //
 #include <boost/preprocessor.hpp>
-#include <sched.h>
+#if defined(__linux) || defined(__linux__)
+# include <sched.h>
+#else
+# define sched_getcpu() '#'
```
Comment (hkaiser) [inline plugins/parcelport/parcelport_logging.hpp]: Wouldn't that break on non-Linux machines?

Comment (hkaiser) [reply plugins/parcelport/parcelport_logging.hpp]: After looking closer: all is fine. Thanks!

**Comment by biddisco** [comment]
Some Appveyor thingy seems to have failed. Do I merge anyway?
