### PR TITLE
Fixes an error with the whitespace check that showed the incorrect location of the error

### LINKED ISSUE #1664: Inspect tool found incorrect endline whitespace
The Inspect tool flagged endline whitespaces in tests/unit/parallel/algorithms/adjacentdifference.cpp at lines 42, 101, 185, 239 from pull request #1659 but no whitespace was found at or near those lines.

### PR DESCRIPTION
**Pull request by Bcorde5**
This fixes #1664

### CODE REVIEW

File: tools/inspect/endline_whitespace_check.cpp [hunk 1]
```diff
@@ -50,7 +53,7 @@ namespace boost
             vector<string> someline, lineorder;
 
 
-            char_separator<char> sep("\n");
+            char_separator<char> sep("\n", "", boost::keep_empty_tokens);
```
Comment (dcbdan) [inline tools/inspect/endline_whitespace_check.cpp]: What is the `""` for?

Comment (Bcorde5) [inline tools/inspect/endline_whitespace_check.cpp]: This is the true culprit, as this allows me to keep the null tokens, so that even if I don't use them, it increases the line number count, so that the line number is actually correct.

**Comment by sithhell** [comment]
Looks good to me and can be merged after rebasing it against master!
