### PR TITLE
Fix memory leak in overlapping relocation test functions (#7184)

### LINKED ISSUE #7184: Memory leak in overlapping relocation test functions
The `setup<T>()` helper allocates two buffers (`mem1`, `mem2`) and returns them as `std::pair<T*, T*>`.

In non-overlapping tests, both buffers are correctly freed:
```cpp
auto [ptr1, ptr2] = setup<trivially_relocatable_struct>();
// ... test ...
std::free(ptr1);
std::free(ptr2);  // ✓ both freed

However, in overlapping tests, the second buffer is captured but never freed:

auto [ptr, ___] = setup<trivially_relocatable_struct_overlapping>();
// ... test uses only ptr ...
std::free(ptr);  // mem2 is leaked

Since overlapping tests only use a single buffer (in-place relocation), the second allocation is unnecessary and gets leaked every time.

Impact
~20 leak sites across multiple relocation test files
Each leak allocates N * sizeof(T) (N = 500)
Repeats across test runs, leading to unnecessary memory usage
Root Cause

setup<T>() was designed for non-overlapping tests that require two buffers.
Overlapping tests reuse a single buffer but still call the same helper, which allocates a second buffer that is never used or freed.

The placeholder binding (___) makes it clear the second value is intentionally ignored, but the allocation still happens.

Affected Areas
uninitialized_relocate.cpp
uninitialized_relocaten.cpp
uninitialized_relocate_backward.cpp
uninitialized_relocate_sender.cpp
uninitialized_relocaten_sender.cpp
uninitialized_relocate_backward_sender.cpp

(affecting test_overlapping() and test_right_overlapping() blocks)

Proposed Fix
Option A — Free the unused buffer (quick fix)
auto [ptr, ptr2_unused] = setup<trivially_relocatable_struct_overlapping>();
// ... test ...
std::free(ptr);
std::free(ptr2_unused);
Option B — Introduce a single-buffer helper (preferred)
template <typename T>
T* setup_single()
{
    clear();
    void* mem = std::malloc(N * sizeof(T));
    HPX_TEST(mem);

    T* ptr = static_cast<T*>(mem);
    for (int i = 0; i < N; i++)
        hpx::construct_at(ptr + i, i);

    HPX_TEST(T::made.size() == N);
    return ptr;
}

Then update overlapping tests to use:

auto ptr = setup_single<trivially_relocatable_struct_overlapping>();
// ... test ...
std::free(ptr);

This avoids unnecessary allocation, makes ownership explicit, and eliminates the risk of leaks.

Happy to submit a PR if this approach looks good

### PR DESCRIPTION
**Pull request by GitMasterJatin**
## Summary

Fixes #7184

The `setup<T>()` helper in relocation test files allocates two buffers (`mem1`, `mem2`) and returns them as `std::pair<T*, T*>`. Non-overlapping tests correctly free both, but overlapping tests only use one buffer for in-place relocation — the second buffer was captured as a discarded binding (`___`) and **never freed**, leaking `N * sizeof(T)` bytes per overlapping test block.

## Changes

Introduced a `setup_single<T>()` helper that allocates only a single buffer for overlapping tests, then updated all overlapping test blocks to use it. This eliminates:
- The unnecessary second allocation
- The silent memory leak
- The misleading discarded binding pattern

### Affected files (6 files, 20 leak sites fixed):

| File | Leak sites |
|------|-----------|
| `uninitialized_relocate.cpp` | 4 (`test_overlapping` x 3, `test_right_overlapping` x 1) |
| `uninitialized_relocaten.cpp` | 4 (`test_overlapping` x 3, `test_right_overlapping` x 1) |
| `uninitialized_relocate_backward.cpp` | 3 (`test_overlapping` x 3) |
| `uninitialized_relocate_sender.cpp` | 3 (`test_overlapping` x 3) |
| `uninitialized_relocaten_sender.cpp` | 3 (`test_overlapping` x 3) |
| `uninitialized_relocate_backward_sender.cpp` | 3 (`test_overlapping` x 3) |

## Testing

Built and ran all 3 available relocation test targets locally (macOS, Apple Clang, Debug build):

```
$ ./bin/uninitialized_relocate_test --hpx:threads=2          # EXIT_CODE=0
$ ./bin/uninitialized_relocaten_test --hpx:threads=2         # EXIT_CODE=0
$ ./bin/uninitialized_relocate_backward_test --hpx:threads=2 # EXIT_CODE=0
```

All tests pass. The sender test targets were not available in this build configuration but the changes are structurally identical.

### CODE REVIEW

File: libs/core/algorithms/tests/unit/algorithms/uninitialized_relocate.cpp [hunk 1]
```diff
@@ -211,6 +211,35 @@ std::pair<T*, T*> setup()
...
+    for (int i = 0; i < N; i++)
+    {
+        hpx::construct_at(ptr + i, i);
+    }
+
+    // N objects constructed
+    HPX_TEST(T::made.size() == N);
+
+    return ptr;
+}
```
Comment (hkaiser) [inline libs/core/algorithms/tests/unit/algorithms/uninitialized_relocate.cpp:241]: Could we avoid the duplication by moving this into a separate header file to be included by all tests, please?

**Comment by hkaiser** [comment]
@GitMasterJatin please pay attention to the CIs, e.g., the clang-format issues reported.

**Comment by GitMasterJatin** [comment]
> @GitMasterJatin please pay attention to the CIs, e.g., the clang-format issues reported.

Done Sir moved all shared test infrastructure ([counted_struct](vscode-file://vscode-app/private/var/folders/bx/l7s83mqj1tb83_j750bf764c0000gn/T/AppTranslocation/9E709B47-2042-470D-B983-FC6644489D1C/d/Visual%20Studio%20Code%202.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html), type aliases, [clear()](vscode-file://vscode-app/private/var/folders/bx/l7s83mqj1tb83_j750bf764c0000gn/T/AppTranslocation/9E709B47-2042-470D-B983-FC6644489D1C/d/Visual%20Studio%20Code%202.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html), [setup<T>()](vscode-file://vscode-app/private/var/folders/bx/l7s83mqj1tb83_j750bf764c0000gn/T/AppTranslocation/9E709B47-2042-470D-B983-FC6644489D1C/d/Visual%20Studio%20Code%202.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html), and [setup_single<T>()](vscode-file://vscode-app/private/var/folders/bx/l7s83mqj1tb83_j750bf764c0000gn/T/AppTranslocation/9E709B47-2042-470D-B983-FC6644489D1C/d/Visual%20Studio%20Code%202.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html)) into a new header [uninitialized_relocate_test_utils.hpp](vscode-file://vscode-app/private/var/folders/bx/l7s83mqj1tb83_j750bf764c0000gn/T/AppTranslocation/9E709B47-2042-470D-B983-FC6644489D1C/d/Visual%20Studio%20Code%202.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) that is included by all 6 test files. Also fixed the clang-format violations. Force-pushed in dd6b670

**Comment by hkaiser** [comment]
@GitMasterJatin unfortunately, inspect is still not happy:
```
/libs/core/algorithms/tests/unit/algorithms/uninitialized_relocate_test_utils.hpp:
    Non-ASCII: (line 55)
```

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Comment by GitMasterJatin** [comment]
> LGTM, thanks!

Thank you Sir
