### PR TITLE
Fixing Problems in MPI parcelport and future serialization.

### LINKED ISSUE #1752: Error in AGAS
I am getting an internal error in the AGAS server when running Octo-Tiger on 128 SuperMIC nodes.

"{what}: primary_namespace::resolve_free_list, failed to resolve gid, gid({0000003c00000001, 0000000002dc13f6}): HPX(internal_server_error)"

The full error output is here:

https://gist.github.com/dmarce1/b25f80106be451972158

This was with the most recent master version of HPX (at least, as of yesterday), Intel 15, MVAPICH2, and boost 1.59, GCC 4.9 headers, tbbmalloc

I will post a version of the code that does not have external library dependencies and which reproduces the error later today. 

Could  this have anything to do with setting the hpx.parcel.max_connections or hpx.parcel.max_connections_per_locality too low?

### PR DESCRIPTION
**Pull request by sithhell**
This PR contains the following:
 - fly-by change to remove unneeded compiler flag related to custom allocators (among the allocators we support, there is no mentioning of the need of those flags)
 - Fixing some bugs in the MPI parcelport
 - Fixing src/version.cpp to work with Intel MPI 
 - Removing a lock held when calling a function that might suspend

I didn't have the chance to actually test if this fixes #1752 as well, but those patches improve the overall correctness of the codebase, and as such I am proposing the PR right now.

### CODE REVIEW

File: src/version.cpp [hunk 1]
```diff
@@ -7,12 +7,13 @@
 ////////////////////////////////////////////////////////////////////////////////
 
 #include <hpx/config/defines.hpp>
-#include <hpx/version.hpp>
 
 #if defined(HPX_HAVE_PARCELPORT_MPI)
 #include <mpi.h>
 #endif
 
+#include <hpx/version.hpp>
```
Comment (K-ballo) [inline src/version.cpp]: If this is yet another order dependent `#include`, please annotate as such to avoid regressions.

**Comment by hkaiser** [comment]
LGTM

**Comment by sithhell** [comment]
The latest commit eliminates a potential cause for negative credits. After testing, this seem to fix #1752 indeed.
