### PR TITLE
Fixing parcel compression, adding test

### LINKED ISSUE #2124: Make a testcase for parcel compression
@hkaiser This is a reminder that we need to make a test case for buildbot for the experimental compression inside hpx.

### PR DESCRIPTION
**Pull request by hkaiser**
- extract registration macros for compression into separate files
- flyby: make client<>::client(future<id_type>&&) non-explicit
- flyby: added HPX_DECLARE_PLAIN_ACTION
- flyby: fix performance counter mix-up of sent bytes and serialized bytes

This also fixes #2124

### CODE REVIEW

**Comment by hkaiser** [comment]
@quantomb This fixes parcel compression. Please verify that it does fix it for you as well.

**Comment by quantomb** [comment]
@hkaiser Working on it. Just to be clear. I need to pull this branch and recompile HPX with this to check your changes correct. That is this has not been merged into master if I am reading Github correctly.

**Comment by aserio** [comment]
@quantomb You will need to switch to this branch to do the test

File: hpx/runtime/actions/plain_action.hpp [hunk 1]
```diff
@@ -169,6 +169,41 @@ namespace hpx { namespace traits
...
+        HPX_DECLARE_PLAIN_ACTION_, HPX_UTIL_PP_NARG(__VA_ARGS__)              \
+    )(__VA_ARGS__))                                                           \
+    /**/
+
+#define HPX_DECLARE_PLAIN_DIRECT_ACTION_(...)                                 \
+    HPX_UTIL_EXPAND_(BOOST_PP_CAT(                                            \
+        HPX_DECLARE_PLAIN_DIRECT_ACTION_, HPX_UTIL_PP_NARG(__VA_ARGS__)       \
+    )(__VA_ARGS__))                                                           \
+    /**/
+
```
Comment (sithhell) [inline hpx/runtime/actions/plain_action.hpp]: This should expand to HPX_DECLARE_PLAIN_ACTION_N shouldn't it?

Comment (hkaiser) [inline hpx/runtime/actions/plain_action.hpp]: Doesn't it expand to `HPX_DECLARE_PLAIN_ACTION_N`, where `N == HPX_UTIL_PP_NARG(__VA_ARGS__)`?

Comment (sithhell) [inline hpx/runtime/actions/plain_action.hpp]: Am 29.04.2016 9:32 nachm. schrieb "Hartmut Kaiser" <notifications@github.com
>:
>
> In hpx/runtime/actions/plain_action.hpp:
>
> > +#define
HPX_DECLARE_PLAIN_DIRECT_ACTION(...)                                  \
> > +
HPX_DECLARE_PLAIN_DIRECT_ACTION_(__VA_ARGS__)                             \
> > +    /**/
> > +
> > +#define
HPX_DECLARE_PLAIN_ACTION_(...)                                        \
> > +
HPX_UTIL_EXPAND_(BOOST_PP_CAT(                                            \
> > +        HPX_DECLARE_PLAIN_ACTION_,
HPX_UTIL_PP_NARG(__VA_ARGS__)              \
> > +
)(__VA_ARGS__))                                                           \
> > +    /**/
> > +
> > +#define
HPX_DECLARE_PLAIN_DIRECT_ACTION_(...)                                 \
> > +
HPX_UTIL_EXPAND_(BOOST_PP_CAT(                                            \
> > +        HPX_DECLARE_PLAIN_DIRECT_ACTION_,
HPX_UTIL_PP_NARG(__VA_ARGS__)       \
> > +
)(__VA_ARGS__))                                                           \
> > +    /**/
> > +
>
> Doesn't it expand to HPX_DECLARE_PLAIN_ACTION_N, where N ==
HPX_UTIL_PP_NARG(__VA_ARGS__)?

I read _DIRECT_ in there.

Comment (hkaiser) [inline hpx/runtime/actions/plain_action.hpp]: > I read _DIRECT_ in there.

Sure. This defines both, the `_DIRECT_` and the non-`_DIRECT_` versions.

Comment (sithhell) [inline hpx/runtime/actions/plain_action.hpp]: OK, looks like I'm overly dense, I can't see that macro definition for DIRECT.

**Comment by quantomb** [comment]
So initial runs indicate that this is working. I have at least one example that seems to show about a 30% compression and a speedup of about 35% compared to the case with compression disabled. I need to go through the other runs more carefully to be sure but this is a promising result.

Note both these cases have parcel coalescing disabled so as to avoid any complications with that not working.

**Comment by hkaiser** [comment]
> So initial runs indicate that this is working. I have at least one example that seems to show about a 30% compression and a speedup of about 35% compared to the case with compression disabled. I need to go through the other runs more carefully to be sure but this is a promising result.

@quantomb Thanks. This however seems to indicate that the current parquet code does not take advantage of zero copy serialization. Enabling compression disables zero copy. Alternatively, the benefit from compressing data over the network outweighs any speedup we gain from zero copy serialization.

File: hpx/runtime/actions/plain_action.hpp (hunk 1 above)
Comment (hkaiser) [inline hpx/runtime/actions/plain_action.hpp]: Sorry, which macro definition do think is missing?

Comment (sithhell) [inline hpx/runtime/actions/plain_action.hpp]: `HPX_DECLARE_PLAIN_DIRECT_ACTION_1` and `HPX_DECLARE_PLAIN_DIRECT_ACTION_2`

Comment (hkaiser) [inline hpx/runtime/actions/plain_action.hpp]: Ok, my bad. Should be fixed now

**Comment by quantomb** [comment]
I need to apologize. The numbers I have do not reflect what I reported on Saturday. I assure you I was looking at the data when I reported it and was comparing something but I don't know what it was. There is a time difference in the simulation although in one instance it is slower and another is faster. Neither of these is by more than 10%. Also there is no noticeable compression in any case. Again I am very frustrated with myself as I don't know what I was seeing Saturday.

**Comment by hkaiser** [comment]
@quantomb So we're not even sure if compression kicks in for you, right?

**Comment by quantomb** [comment]
Currently compression does not appear to kick in. At least if I am reading the performance counters correctly. Again, I apologize for the misleading response on Saturday.
