### PR TITLE
Resolved memory leak in stencil_8

### LINKED ISSUE #2121: Possible memory leak in 1d_stencil_8
The example 1d_stencil_8 uses a custom allocator (partition_allocator) for the serialize_buffer inside the partition_data. The custom deleter is passed to the underlying boost::shared_array.

The problem:
The custom deleter is not called at all allocated memory. The reference count of the boost::shared_array is 3 before the last partition_data goes out of scope. There are still 2 references somewhere which lifetimes exceed the hpx_main. When the static allocator is destroyed the `heap_` is empty for `nt=0`. For any `nt` the `heap_` contains less elements than allocated via` new T[n]`. The `heap_` should contain all.

1d_stencil_8_1.cpp: output with arguments --nt 0 --np 1:
> allocate called
> ~partition_data(): use_count before destruction = 4
> leaving hpx_main
> ~partition_data(): use_count before destruction = 3
> hpx_main finished
> ~partition_allocator(): new_counter = 1
> ~partition_allocator(): heap_.size() = 0

The problem is not that the wrong deleter is called. When I added a static shared_array (tracker) in 1d_stencil_8_2.cpp to the allocator, to keep track of the use_count, I found out, that there is still **one** reference left (not including the static one) when the allocator is destroyed.

1d_stencil_8_2.cpp: output with arguments --nt 0 --np 1:
> allocate called
> ~partition_data(): use_count before destruction = 4
> ~partition_data(): use_count before destruction = 5
> leaving hpx_main
> ~partition_data(): use_count before destruction = 4
> hpx_main finished
> ~partition_allocator(): tracker.use_count() = 2
> ~partition_allocator(): new_counter = 1
> ~partition_allocator(): heap_.size() = 0

The printed use count should be 1 not 2, since "tracker" is the only reference left.

Summary: The custom deleter of partition_allocator is not called often enough, thus the `heap_` does not contain all pointers.
The reference count of the boost::shared_array is **2** after hpx_main finished and when the static allocator gets destroyed it is still **1**. Maybe some cyclic references going on?

Files: [1d_stencil_8_X.zip](https://github.com/STEllAR-GROUP/hpx/files/236676/1d_stencil_8_X.zip)
OS: Linux Mint 17 Qiana 64 bit
HPX revision: 1c4416c9b2f9ae9fa8339713cb122396d1bd2315
Boost version: 1.58

### PR DESCRIPTION
**Pull request by hkaiser**
- flyby: change gather API to rely on clients instead of future<id_type>
- flyby: fixed one of the register_with_basename API overloads

This fixes #2121

### CODE REVIEW

**Comment by hkaiser** [comment]
@markusobi Please verify whether this change fixes your problems

File: hpx/lcos/local/receive_buffer.hpp [hunk 1]
```diff
@@ -147,6 +147,13 @@ namespace hpx { namespace lcos { namespace local
             entry->set_value(std::move(val));
         }
 
+        // explicitly clear all sored data
```
Comment (sithhell) [inline hpx/lcos/local/receive_buffer.hpp]: Typo here

File: hpx/lcos/local/receive_buffer.hpp [hunk 2]
```diff
@@ -147,6 +147,13 @@ namespace hpx { namespace lcos { namespace local
...
+        void clear_all()
+        {
+            std::lock_guard<mutex_type> l(mtx_);
+            buffer_map_.clear();
```
Comment (sithhell) [inline hpx/lcos/local/receive_buffer.hpp]: This clear shouldn't be needed. I think it should be an invariant of that class that the buffer_map is empty on destruction.

File: examples/1d_stencil/1d_stencil_8.cpp [hunk 3]
```diff
@@ -353,6 +357,18 @@ struct stepper_server : hpx::components::component_base<stepper_server>
     HPX_DEFINE_COMPONENT_ACTION(stepper_server, from_right, from_right_action);
     HPX_DEFINE_COMPONENT_ACTION(stepper_server, from_left, from_left_action);
 
+    // release dependencies
+    void release_dependencies()
+    {
+        left_ = hpx::shared_future<hpx::id_type>();
+        right_ = hpx::shared_future<hpx::id_type>();
```
Comment (sithhell) [inline examples/1d_stencil/1d_stencil_8.cpp]: This looks like the perfect candidate for "weak" or unmanaged GIDs

Comment (hkaiser) [inline examples/1d_stencil/1d_stencil_8.cpp]: Not sure. Each locality has to keep the partitions on the neighboring localities alive. OTOH, the user could ensure that by other, indirect means.

File: hpx/lcos/local/receive_buffer.hpp (hunk 2 above)
Comment (hkaiser) [inline hpx/lcos/local/receive_buffer.hpp]: The point is to be able to clear it before destruction as any stored `future<id_type>` could participate in circular references.

Comment (sithhell) [inline hpx/lcos/local/receive_buffer.hpp]: The receive buffer itself doesn't know about future<id_type>. I think it should be a error if the receive buffer leaves non collected data behind. In the case of the stencil example, this should be stuff sent on the last time step but never received, iiuc.

File: examples/1d_stencil/1d_stencil_8.cpp (hunk 3 above)
Comment (sithhell) [inline examples/1d_stencil/1d_stencil_8.cpp]: Right. In this example, it's ensured (or should be) by the timestep synchronization with the left and right neighbor.

Comment (hkaiser) [inline examples/1d_stencil/1d_stencil_8.cpp]: At this point I don't know how to make unmanaged the `id_type` stored in a future. Please advise.

Comment (sithhell) [inline examples/1d_stencil/1d_stencil_8.cpp]: I don't know either :/
In this case however, i'd even advise to not use futures at all for left_ and right_. This might be a source of unnecessary overhead.
In the general case, this was more a plug for better client types ;)

Comment (hkaiser) [inline examples/1d_stencil/1d_stencil_8.cpp]: `hpx::find_from_basename()` returns `future<id_type>`. Do you suggest to call `get()` on the returned futures?

Comment (hkaiser) [inline examples/1d_stencil/1d_stencil_8.cpp]: > In the general case, this was more a plug for better client types ;)

I have not seen any viable alternative to what we have yet.
