### PR TITLE
Move tests to modules

### LINKED ISSUE #4046: Move tests left behind to respective modules
During the recent modularization efforts we have left behind some of the tests that should be part of the modules. Here is a list of those (there could be more):

- module `datastructures`:
  - [x] `unit/util/tuple.cpp` (#4079)
  - [x] `regression/util/optional_swap_3200.cpp` (#4079)
  - [x] `regression/util/tuple_serialization_803.cpp` (#4079)
  - [x] `unit/traits/is_tuple_like.cpp` (#4049)

- module `errors`:
  - [x] `unit/diagnostics/exception.cpp` (#4049)
  - [ ] `unit/diagnostics/handled_exception.cpp` (#4570)
  - [ ] `unit/diagnostics/unhandled_exception.cpp` (#4570)

- module `iterator_support`:
  - [x] `unit/util/iterator/iterator_adaptor.cpp` (#4079)
  - [x] `unit/util/iterator/iterator_facade.cpp` (#4079)
  - [x] `unit/util/iterator/stencil3_iterator.cpp` (#4179)
  - [x] `unit/util/iterator/transform_iterator.cpp` (#4179)
  - [x] `unit/util/iterator/transform_iterator2.cpp` (#4179)

### PR DESCRIPTION
**Pull request by msimberg**
Moves more tests to modules. Fixes #4046 and a few more. There are still some tests left that I'm undecided about.

### CODE REVIEW

File: libs/concurrency/tests/unit/lockfree_fifo.cpp [hunk 1]
```diff
@@ -59,29 +60,30 @@ void worker_thread(std::uint64_t num_thread)
...
-         "the number of worker threads inserting objects into the fifo")
-        ("items,i", value<std::uint64_t>(&items)->default_value(500000),
-         "the number of items to create per queue")
-    ;
+    desc_cmdline.add_options()(
+        "help,h", "print out program usage (this message)")("threads,t",
+        value<std::uint64_t>(&threads)->default_value(2),
+        "the number of worker threads inserting objects into the fifo")(
+        "items,i", value<std::uint64_t>(&items)->default_value(500000),
+        "the number of items to create per queue");
```
Comment (hkaiser) [inline libs/concurrency/tests/unit/lockfree_fifo.cpp:80]: I know it's annoying, but could we 'clang-unformat' the command line options, please?

Comment (msimberg) [reply libs/concurrency/tests/unit/lockfree_fifo.cpp:80]: Yeah, no worries :) I left this as a draft exactly for these kind of things. I'll fix it.
