### PR TITLE
Fix bulk_construct with count = 0

### LINKED ISSUE #3267: tests.unit.host_.block_allocator fails occasionally
Another one which fails occasionally, but consistently. Typical output:

```
srun: Warning: can't run 1 processes on 2 nodes, setting nnodes to 1
using seed: 1538746038
{stack-trace}: 22 frames:
0x7f66f5acd9c1  : ??? + 0x7f66f5acd9c1 in /home/buildbot/rostam/slave_rostam/hpx_gcc_5_boost_1_62_centos_x86_64_debug/build/lib/libhpxd.so.1
0x7f66f5acdb18  : ??? + 0x7f66f5acdb18 in /home/buildbot/rostam/slave_rostam/hpx_gcc_5_boost_1_62_centos_x86_64_debug/build/lib/libhpxd.so.1
0x7f66f5b464ec  : hpx::termination_handler(int) + 0x29a in /home/buildbot/rostam/slave_rostam/hpx_gcc_5_boost_1_62_centos_x86_64_debug/build/lib/libhpxd.so.1
0x7f66f3f535e0  : ??? + 0x7f66f3f535e0 in /usr/lib64/libpthread.so.0
0x4350d0        : ??? + 0x4350d0 in /home/buildbot/rostam/slave_rostam/hpx_gcc_5_boost_1_62_centos_x86_64_debug/build/bin/block_allocator_test
0x432808        : ??? + 0x432808 in /home/buildbot/rostam/slave_rostam/hpx_gcc_5_boost_1_62_centos_x86_64_debug/build/bin/block_allocator_test
0x430920        : ??? + 0x430920 in /home/buildbot/rostam/slave_rostam/hpx_gcc_5_boost_1_62_centos_x86_64_debug/build/bin/block_allocator_test
0x42e390        : ??? + 0x42e390 in /home/buildbot/rostam/slave_rostam/hpx_gcc_5_boost_1_62_centos_x86_64_debug/build/bin/block_allocator_test
0x42bfaf        : ??? + 0x42bfaf in /home/buildbot/rostam/slave_rostam/hpx_gcc_5_boost_1_62_centos_x86_64_debug/build/bin/block_allocator_test
0x429846        : ??? + 0x429846 in /home/buildbot/rostam/slave_rostam/hpx_gcc_5_boost_1_62_centos_x86_64_debug/build/bin/block_allocator_test
0x424953        : ??? + 0x424953 in /home/buildbot/rostam/slave_rostam/hpx_gcc_5_boost_1_62_centos_x86_64_debug/build/bin/block_allocator_test
0x42f7d1        : ??? + 0x42f7d1 in /home/buildbot/rostam/slave_rostam/hpx_gcc_5_boost_1_62_centos_x86_64_debug/build/bin/block_allocator_test
0x7f66f5b21546  : ??? + 0x7f66f5b21546 in /home/buildbot/rostam/slave_rostam/hpx_gcc_5_boost_1_62_centos_x86_64_debug/build/lib/libhpxd.so.1
0x7f66f5b1dce3  : ??? + 0x7f66f5b1dce3 in /home/buildbot/rostam/slave_rostam/hpx_gcc_5_boost_1_62_centos_x86_64_debug/build/lib/libhpxd.so.1
0x7f66f5b11cd9  : ??? + 0x7f66f5b11cd9 in /home/buildbot/rostam/slave_rostam/hpx_gcc_5_boost_1_62_centos_x86_64_debug/build/lib/libhpxd.so.1
0x7f66f5b59ae9  : hpx::runtime_impl::run_helper(hpx::util::function<int (), false> const&, int&) + 0x533 in /home/buildbot/rostam/slave_rostam/hpx_gcc_5_boost_1_62_centos_x86_64_debug/build/lib/libhpxd.so.1
0x7f66f5b7bd26  : ??? + 0x7f66f5b7bd26 in /home/buildbot/rostam/slave_rostam/hpx_gcc_5_boost_1_62_centos_x86_64_debug/build/lib/libhpxd.so.1
0x7f66f5b7995b  : ??? + 0x7f66f5b7995b in /home/buildbot/rostam/slave_rostam/hpx_gcc_5_boost_1_62_centos_x86_64_debug/build/lib/libhpxd.so.1
0x7f66f5b722ac  : ??? + 0x7f66f5b722ac in /home/buildbot/rostam/slave_rostam/hpx_gcc_5_boost_1_62_centos_x86_64_debug/build/lib/libhpxd.so.1
0x7f66f6306b05  : hpx::threads::coroutines::detail::coroutine_impl::operator()() + 0xc5 in /home/buildbot/rostam/slave_rostam/hpx_gcc_5_boost_1_62_centos_x86_64_debug/build/lib/libhpxd.so.1
0x7f66f636cd1b  : ??? + 0x7f66f636cd1b in /home/buildbot/rostam/slave_rostam/hpx_gcc_5_boost_1_62_centos_x86_64_debug/build/lib/libhpxd.so.1
{what}: Floating point exception
{config}:
  HPX_WITH_AGAS_DUMP_REFCNT_ENTRIES=OFF
  HPX_WITH_APEX=OFF
  HPX_WITH_ATTACH_DEBUGGER_ON_TEST_FAILURE=OFF
  HPX_WITH_AUTOMATIC_SERIALIZATION_REGISTRATION=ON
  HPX_WITH_CXX14_RETURN_TYPE_DEDUCTION=TRUE
  HPX_WITH_GOOGLE_PERFTOOLS=OFF
  HPX_WITH_INCLUSIVE_SCAN_COMPATIBILITY=ON
  HPX_WITH_IO_COUNTERS=ON
  HPX_WITH_IO_POOL=ON
  HPX_WITH_ITTNOTIFY=OFF
  HPX_WITH_LOGGING=ON
  HPX_WITH_MORE_THAN_64_THREADS=OFF
  HPX_WITH_NATIVE_TLS=ON
  HPX_WITH_NETWORKING=ON
  HPX_WITH_PAPI=On
  HPX_WITH_PARCELPORT_ACTION_COUNTERS=OFF
  HPX_WITH_PARCELPORT_LIBFABRIC=OFF
  HPX_WITH_PARCELPORT_MPI=On
  HPX_WITH_PARCELPORT_MPI_MULTITHREADED=ON
  HPX_WITH_PARCELPORT_TCP=ON
  HPX_WITH_PARCELPORT_VERBS=OFF
  HPX_WITH_PARCEL_COALESCING=ON
  HPX_WITH_PARCEL_PROFILING=OFF
  HPX_WITH_SCHEDULER_LOCAL_STORAGE=OFF
  HPX_WITH_SPINLOCK_DEADLOCK_DETECTION=OFF
  HPX_WITH_STACKOVERFLOW_DETECTION=ON
  HPX_WITH_STACKTRACES=ON
  HPX_WITH_SWAP_CONTEXT_EMULATION=OFF
  HPX_WITH_THREAD_BACKTRACE_ON_SUSPENSION=OFF
  HPX_WITH_THREAD_CREATION_AND_CLEANUP_RATES=OFF
  HPX_WITH_THREAD_CUMULATIVE_COUNTS=ON
  HPX_WITH_THREAD_DEBUG_INFO=OFF
  HPX_WITH_THREAD_DESCRIPTION_FULL=OFF
  HPX_WITH_THREAD_GUARD_PAGE=ON
  HPX_WITH_THREAD_IDLE_RATES=OFF
  HPX_WITH_THREAD_LOCAL_STORAGE=OFF
  HPX_WITH_THREAD_MANAGER_IDLE_BACKOFF=ON
  HPX_WITH_THREAD_QUEUE_WAITTIME=OFF
  HPX_WITH_THREAD_STACK_MMAP=ON
  HPX_WITH_THREAD_STEALING_COUNTS=ON
  HPX_WITH_THREAD_TARGET_ADDRESS=OFF
  HPX_WITH_TIMER_POOL=ON
  HPX_WITH_TUPLE_RVALUE_SWAP=ON
  HPX_WITH_UNWRAPPED_COMPATIBILITY=ON
  HPX_WITH_VALGRIND=OFF
  HPX_WITH_VERIFY_LOCKS=OFF
  HPX_WITH_VERIFY_LOCKS_BACKTRACE=OFF
  HPX_WITH_VERIFY_LOCKS_GLOBALLY=OFF

  HPX_PARCEL_MAX_CONNECTIONS=512
  HPX_PARCEL_MAX_CONNECTIONS_PER_LOCALITY=4
  HPX_AGAS_LOCAL_CACHE_SIZE=4096
  HPX_HAVE_MALLOC=tcmalloc
  HPX_PREFIX (configured)=/home/buildbot/rostam/slave_rostam/hpx_gcc_5_boost_1_62_centos_x86_64_debug/build
  HPX_PREFIX=/home/buildbot/rostam/slave_rostam/hpx_gcc_5_boost_1_62_centos_x86_64_debug/build
{version}: V1.2.0-trunk (AGAS: V3.0), Git: f72a61cce6
{boost}: V1.62.0
{build-type}: debug
{date}: Mar 29 2018 04:49:27
{platform}: linux
{compiler}: GNU C++ version 5.4.0
{stdlib}: GNU libstdc++ version 20160603
srun: error: marvin00: task 0: Aborted (core dumped)
srun: Terminating job step 2017038.473
Base command is "/home/buildbot/rostam/slave_rostam/hpx_gcc_5_boost_1_62_centos_x86_64_debug/build/bin/block_allocator_test --hpx:threads=1 --hpx:localities=1"
Executing command: srun -K -n 1 /home/buildbot/rostam/slave_rostam/hpx_gcc_5_boost_1_62_centos_x86_64_debug/build/bin/block_allocator_test --hpx:threads=1 --hpx:localities=1
```

### PR DESCRIPTION
**Pull request by msimberg**
Fixes #3267.

## Proposed Changes

- Make `bulk_construct` and `bulk_destroy` no-ops if `count` is `0`.

### CODE REVIEW

**Comment by msimberg** [comment]
`malloc` should allow 0-sized allocations, but `hwloc_alloc` clearly doesn't. May be due to `memalign` inside `hwloc_alloc` but couldn't find anything to support this.

**Comment by hkaiser** [comment]
The allocator itself may have to be made resilient against 0-sized allocations (which is perfectly valid, btw).

**Comment by hkaiser** [comment]
So it's a hwloc bug after all, or should we call it a 'technology gap'?

**Comment by msimberg** [comment]
That was my conclusion after a quick check, yes. I'll double check and report to them. Ideally hwloc would just allow 0-sized allocations so we don't need to do any workarounds.

**Comment by msimberg** [comment]
I looked into this properly and it's not hwloc's fault. The problem is in the chunker (makes more sense considering the floating point exception). The problem is [here](https://github.com/STEllAR-GROUP/hpx/blob/e122fddeb27977f24fe6904de4e4910745e6232a/hpx/parallel/util/detail/chunk_size.hpp#L108-L109) (called via `bulk_construct`).

I guess if allocation is allowed with size 0, then construction and destruction should be as well?

**Comment by hkaiser** [comment]
@msimberg Thanks for investigating, If `count == 0` construction/destruction should be just no-ops.

**Comment by msimberg** [comment]
Updated. I added an explicit test case for `count = 0` as well.

File: tests/unit/computeapi/host/block_allocator.cpp [hunk 1]
```diff
@@ -78,7 +78,7 @@ int hpx_main(boost::program_options::variables_map& vm)
 
     std::cout << "using seed: " << seed << std::endl;
     std::mt19937 gen(seed);
-    std::uniform_int_distribution<> dis(0, 511);
+    std::uniform_int_distribution<> dis(1, 512);
```
Comment (hkaiser) [inline tests/unit/computeapi/host/block_allocator.cpp]: Shouldn't we now leave the original code in place?

Comment (msimberg) [reply tests/unit/computeapi/host/block_allocator.cpp]: I'm fine with that as well. I thought it's nicer to have two separate cases, one for `count = 0` and one for `count != 0` so that in case there's a useful stacktrace one can see which case failed, but don't mind changing it back either.

Comment (hkaiser) [reply tests/unit/computeapi/host/block_allocator.cpp]: Sure, makes sense.
