### PR TITLE
Fix building on musl.

### LINKED ISSUE #5946: dll_dlopen.hpp: error: RTLD_DI_ORIGIN was not declared in this scope with musl libc
## Expected Behavior

Successfully build with musl libc

## Actual Behavior

Fails to build with musl libc. With error ```sys-cluster/hpx-1.7.1-r1 - /.../dll_dlopen.hpp: error: RTLD_DI_ORIGIN was not declared in this scope```. The reason is that RTLD_DI_ORIGIN is not present in musl.

## Steps to Reproduce the Problem

1. Build hpx with from source with musl libc

## Specifications

  - HPX Version: 1.8.0
  - Compiler: g++
  - OS: Gentoo
  - libc: musl

Complete build log: https://829242.bugs.gentoo.org/attachment.cgi?id=759092.

With help from my mentors, I came up with this patch (I'm a Google Summer of Code 22 student). I'm happy to send in a PR if devs think it's appropriate.

```diff
--- a/libs/core/plugin/include/hpx/plugin/detail/dll_dlopen.hpp
+++ b/libs/core/plugin/include/hpx/plugin/detail/dll_dlopen.hpp
@@ -319,20 +319,8 @@ namespace hpx { namespace util { namespace plugin {
             std::string result;

 #if !defined(__ANDROID__) && !defined(ANDROID) && !defined(__APPLE__)
-            char directory[PATH_MAX] = {'\0'};
             const_cast<dll&>(*this).LoadLibrary(ec);
-            if (!ec && ::dlinfo(dll_handle, RTLD_DI_ORIGIN, directory) < 0)
-            {
-                std::string str = hpx::util::format(
-                    "Hpx.Plugin: Could not extract path the shared library "
-                    "'{}' has been loaded from (dlerror: {})",
-                    dll_name, dlerror());
-
-                HPX_THROWS_IF(
-                    ec, filesystem_error, "plugin::get_directory", str);
-            }
-            result = directory;
-            ::dlerror();    // Clear the error state.
+            result = path(dll_name).parent_path().string();
 #elif defined(__APPLE__)
             // SO staticfloat's solution
             const_cast<dll&>(*this).LoadLibrary(ec);
```

With this patch, it builds on both musl and glibc systems.

### PR DESCRIPTION
**Pull request by listout**
These are some patches that make it possible to build hpx on musl.

Signed-off-by: brahmajit das <brahmajit.xyz@gmail.com>

Fixes #5946

## Proposed Changes

- EXEC_PAGESIZE is not defined under musl so including linux/param.h
  where it should be defined. Header linux/param.h does not depend on
  any libc and hence can use included on any linux system.
- execinfo.h is only present on glibc and ulibc, but not on musl so
  before defining HPX_HAVE_EXECINFO it's being checked whether we're on
  a glibc or ulibc system
- RTLD_DI_ORIGIN is not present on musl, hence the alternate
  the solution is implemented if RTLD_DI_ORIGIN is undefined.

## Any background context you want to provide?

hpx was failing to build with musl libc, these patches should fix them without affecting other libc systems

## Checklist

- [ ] I have added a new feature and have added tests to go along with it.
- [ ] I have fixed a bug and have added a regression test.
- [ ] I have added a test using random numbers; I have made sure it uses a seed, and that random numbers generated are valid inputs for the tests.

### CODE REVIEW

File: libs/core/plugin/include/hpx/plugin/detail/dll_dlopen.hpp [hunk 1]
```diff
@@ -319,8 +319,11 @@ namespace hpx { namespace util { namespace plugin {
             std::string result;
 
 #if !defined(__ANDROID__) && !defined(ANDROID) && !defined(__APPLE__)
+#if defined(RTLD_DI_ORIGIN)
             char directory[PATH_MAX] = {'\0'};
+#endif
             const_cast<dll&>(*this).LoadLibrary(ec);
+#if defined(RTLD_DI_ORIGIN)
```
Comment (hkaiser) [inline libs/core/plugin/include/hpx/plugin/detail/dll_dlopen.hpp:326]: I think you could join the two `#ifdef` sections above (reorder the lines).

File: libs/core/debugging/src/backtrace.cpp [hunk 2]
```diff
@@ -19,7 +19,9 @@
 
 #if (defined(__linux) || defined(__APPLE__) || defined(__sun)) &&              \
     (!defined(__ANDROID__) || !defined(ANDROID))
+#if (defined(__GLIBC__))
```
Comment (hkaiser) [inline libs/core/debugging/src/backtrace.cpp:22]:
```suggestion
#if defined(__GLIBC__)
```

**Review by hkaiser — CHANGES_REQUESTED** [review]

**Comment by listout** [comment]
@hkaiser Would like to report that the tests pass when I ran them locally with these patches, both on musl and glibc

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Comment by listout** [comment]
@hkaiser Looks like some of the tests failed, mainly the tests.unit2. I can there's a backtrace.

**Comment by hkaiser** [comment]
> @hkaiser Looks like some of the tests failed, mainly the tests.unit2. I can there's a backtrace.

That failure is a known issue and unrelated to your PR. Feel free to ignore it.

**Comment by hkaiser** [comment]
bors merge

**Comment by hkaiser** [comment]
@listout Congratulations, your first PR to the HPX repository has just been merged! As a 'thank you' we offer a free STE||AR-Group t-shirt to all of our first-time contributors. If you are interested in receiving one, please get back to me directly so we can set up the delivery.

**Comment by listout** [comment]
@hkaiser OMG that's so great. How should I contact you, can I send you a mail at `hkaiser at cct dot lsu dot edu`?

**Comment by hkaiser** [comment]
> @hkaiser OMG that's so great. How should I contact you, can I send you a mail at `hkaiser at cct dot lsu dot edu`?

Yes, that will work.

**Comment by listout** [comment]
@hkaiser if you receive an email from `brahmajit.xyz at gmail dot com`, that will be.
