### PR TITLE
fix scheduler_executor bulk

### LINKED ISSUE #7022: scheduler_executor performance regression with stdexec integration
After PR #6746 (stdexec integration), scheduler_executor benchmarks 
report '---' instead of actual timings. This is caused by:

1. stdexec API changes (__starts_on namespace, sender_expr_for deprecation, 
   transform_sender signature)
2. Bulk operations requiring integral shapes and execution policies

### PR DESCRIPTION
**Pull request by charan-003**
Fix scheduler_executor benchmarks

Fixes #7022

### CODE REVIEW

File: libs/core/executors/include/hpx/executors/explicit_scheduler_executor.hpp [hunk 1]
```diff
@@ -206,8 +211,22 @@ namespace hpx::execution::experimental {
 
             if constexpr (std::is_void_v<result_type>)
             {
+#if defined(HPX_HAVE_STDEXEC)
+                // stdexec::bulk requires integral shape and execution policy
+                using size_type = decltype(util::size(shape));
+                size_type const n = util::size(shape);
+                return bulk(schedule(exec.sched_), par, n,
```
Comment (hkaiser) [inline libs/core/executors/include/hpx/executors/explicit_scheduler_executor.hpp:219]: Why is this neccesary?

File: libs/core/executors/include/hpx/executors/explicit_scheduler_executor.hpp [hunk 2]
```diff
@@ -206,8 +211,22 @@ namespace hpx::execution::experimental {
...
+                    [shape,
+                        bound_f = hpx::bind_back(HPX_FORWARD(F, f),
+                            HPX_FORWARD(Ts, ts)...)](size_type i) mutable {
+                        auto it = util::begin(shape);
+                        std::advance(it, i);
+                        HPX_INVOKE(bound_f, *it);
+                    });
```
Comment (hkaiser) [inline libs/core/executors/include/hpx/executors/explicit_scheduler_executor.hpp]: Couldn't you directly capture the template parameter pack:
```suggestion
                    [shape, f = HPX_FORWARD(F, f),  
                        ... args = HPX_FORWARD(Ts, ts)...](size_type i) mutable {
                        auto it = std::begin(shape);
                        HPX_INVOKE(f, *std::next(it, i), args...);
```

File: libs/core/executors/include/hpx/executors/explicit_scheduler_executor.hpp (hunk 1 above)
Comment (charan-003) [reply libs/core/executors/include/hpx/executors/explicit_scheduler_executor.hpp:219]: as per
https://github.com/NVIDIA/stdexec/blob/5076be2b35de2e78330201b888d82c81b8cb428b/include/stdexec/__detail/__bulk.hpp#L205-L216

`stdexec::bulk` requires integral shapes

**Comment by hkaiser** [comment]
@charan-003 please address the clang-format and inspect issues reported.

**Comment by isidorostsa** [comment]
LGTM too, nice work
