### PR TITLE
Fix numa allocator test 7027

### LINKED ISSUE #7027: Fix failing test related to numa_allocator
We're seeing occasional test failures for our tests related to the numa_allocator (target: tests.unit.modules.compute_local.numa_allocator). We should try to identify the problem and fix it. I'll add an example link here as soon as I see the error again.

### PR DESCRIPTION
**Pull request by GitMasterJatin**
Fixes #7027

Changes made:

numa_allocator.hpp

- Integer division truncation fixed — last executor partition now covers cnt % num_executors remainder elements so no pages go untouched
- Dangling topo_ reference removed — now calls hpx::threads::get_topology() directly in allocate() and deallocate(), no more stored reference member

numa_binding_allocator.hpp
 3. UB volatile read eliminated — *vaddr = *vaddr (reading uninitialized memory, optimizable to no-op) replaced with *reinterpret_cast<volatile char*>(page_ptr) = 0 — a guaranteed physical write that triggers first-touch

The <DEB> log lines in the test output are expected (test has #define QUEUE_HOLDER_NUMA_DEBUG true).

## Checklist

Not all points below apply to all pull requests.

- [ ] I have added a new feature and have added tests to go along with it.
- [ ] I have fixed a bug and have added a regression test.
- [ ] I have added a test using random numbers; I have made sure it uses a seed, and that random numbers generated are valid inputs for the tests.

### CODE REVIEW

**Comment by hkaiser** [comment]
Excellent analysis! Thanks!

**Comment by hkaiser** [comment]
@GitMasterJatin Did you by any chance look into the page size issue @LSUDOKO mentioned here: https://github.com/STEllAR-GROUP/hpx/issues/7027#issuecomment-4063748281?

**Comment by hkaiser** [comment]
@GitMasterJatin clang-format is not happy, also your changes break compilation.

**Comment by GitMasterJatin** [comment]
Yes @hkaiser Sir, I've addressed the page size concern raised by @LSUDOKO in this updated commit.

In get_numa_domain(), the assertion:

HPX_ASSERT((reinterpret_cast<std::size_t>(page) & 4095) == 0);
was hardcoded to assume 4KB pages. I've replaced it with:

HPX_ASSERT(
    (reinterpret_cast<std::size_t>(page) &
        (threads::get_memory_page_size() - 1)) == 0);
This makes the alignment check correct on any platform regardless of page size.

Regarding the move_pages / -ENOENT concern @LSUDOKO raised (pages returning - when not yet faulted): this is actually addressed by our fix #3 (the touch_pages UB fix). By writing *reinterpret_cast<volatile char*>(page_ptr) = 0 instead of the old *vaddr = *vaddr, we guarantee every page is faulted into RAM before the test queries get_page_numa_domains(). So the -ENOENT path should no longer be hit in practice.

I've also fixed a compilation error (lambda [i] was missing this needed for executors_[i] in the HPX_DEBUG path), applied clang-format, and removed accidentally committed Testing/Temporary/ files.

File: libs/core/compute_local/include/hpx/compute_local/host/numa_allocator.hpp [hunk 1]
```diff
@@ -53,15 +53,14 @@ namespace hpx::parallel::util {
             using other = numa_allocator<U, Executors>;
         };
 
-        numa_allocator(Executors const& executors, hpx::threads::topology& topo)
+        numa_allocator(
+            Executors const& executors, hpx::threads::topology& /* topo */)
```
Comment (hkaiser) [inline libs/core/compute_local/include/hpx/compute_local/host/numa_allocator.hpp:57]: While I have no issues with this as it doesn't really change anything (the reference that was used to construct the allocator was stable after all), I'd like to know if you were seeing actual problem that triggered this modification.

Comment (GitMasterJatin) [reply libs/core/compute_local/include/hpx/compute_local/host/numa_allocator.hpp:57]: @hkaiser Sir you're right that in the existing call sites the reference is stable (the topology singleton lives for the entire HPX runtime lifetime).

I did not observe an actual crash or test failure triggered specifically by this issue. The concern was theoretical: a hypothetical future use of numa_allocator where a caller constructs it with a locally-scoped topology object and then lets async first-touch tasks outlive it. In practice, with HPX's singleton topology, this cannot happen.

Comment (GitMasterJatin) [reply libs/core/compute_local/include/hpx/compute_local/host/numa_allocator.hpp:57]: It doesn't change observable behavior, I'm happy to revert this specific change and keep only the two fixes that actually address the observed intermittent test failures.

Comment (hkaiser) [reply libs/core/compute_local/include/hpx/compute_local/host/numa_allocator.hpp:57]: That's fine. Please leave it in place as you have it.

**Comment by GitMasterJatin** [comment]
Thanks @hkaiser Sir for reviewing and closing the issue
