### PR TITLE
fix(stdexec): added adaption to ensure successful build with stdexec

### LINKED ISSUE #6842: Errors when building tests relying on stdexec
## Description
Errors appeared when I was trying to build tests about `std::execution`.
```
In file included from /Users/Nan/GSoC/hpx/libs/core/execution_base/include/hpx/execution_base/sender.hpp:13,
                 from /Users/Nan/GSoC/hpx/libs/core/execution_base/include/hpx/execution_base/this_thread.hpp:13,
                 from /Users/Nan/GSoC/hpx/libs/core/execution_base/src/agent_ref.cpp:9:
/Users/Nan/GSoC/hpx/libs/core/execution_base/include/hpx/execution_base/stdexec_forward.hpp:165:35: error: 'dependent_domain' has not been declared in 'stdexec'
  165 |     HPX_CXX_EXPORT using stdexec::dependent_domain;
      |                                   ^~~~~~~~~~~~~~~~
/Users/Nan/GSoC/hpx/libs/core/execution_base/include/hpx/execution_base/stdexec_forward.hpp:240:35: error: 'make_completion_signatures' has not been declared in 'stdexec'
  240 |     HPX_CXX_EXPORT using stdexec::make_completion_signatures;
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/Nan/GSoC/hpx/libs/core/execution_base/include/hpx/execution_base/stdexec_forward.hpp:245:35: error: 'transform_env' has not been declared in 'stdexec'
  245 |     HPX_CXX_EXPORT using stdexec::transform_env;
      |                                   ^~~~~~~~~~~~~
In file included from /Users/Nan/GSoC/hpx/libs/core/execution_base/include/hpx/execution_base/any_sender.hpp:12,
                 from /Users/Nan/GSoC/hpx/build/libs/core/execution_base/include/hpx/modules/execution_base.hpp:17,
                 from /Users/Nan/GSoC/hpx/libs/core/execution_base/include/hpx/execution_base/this_thread.hpp:87:
/Users/Nan/GSoC/hpx/libs/core/execution_base/include/hpx/execution_base/completion_signatures.hpp:512:54: warning: 'using stdexec::empty_env = struct stdexec::__env::env<>' is deprecated: stdexec::empty_env is now spelled stdexec::env<> [-Wdeprecated-declarations]
  512 |         typename Env = hpx::execution::experimental::empty_env>
      |                                                      ^~~~~~~~~
In file included from /Users/Nan/GSoC/hpx/build/_deps/stdexec-src/include/stdexec/execution.hpp:18,
                 from /Users/Nan/GSoC/hpx/libs/core/execution_base/include/hpx/execution_base/stdexec_forward.hpp:35:
/Users/Nan/GSoC/hpx/build/_deps/stdexec-src/include/stdexec/__detail/__execution_fwd.hpp:102:9: note: declared here
  102 |   using empty_env [[deprecated("stdexec::empty_env is now spelled stdexec::env<>")]] = env<>;
      |         ^~~~~~~~~
/Users/Nan/GSoC/hpx/libs/core/execution_base/include/hpx/execution_base/completion_signatures.hpp:520:54: warning: 'using stdexec::empty_env = struct stdexec::__env::env<>' is deprecated: stdexec::empty_env is now spelled stdexec::env<> [-Wdeprecated-declarations]
  520 |         typename Env = hpx::execution::experimental::empty_env>
      |                                                      ^~~~~~~~~
/Users/Nan/GSoC/hpx/build/_deps/stdexec-src/include/stdexec/__detail/__execution_fwd.hpp:102:9: note: declared here
  102 |   using empty_env [[deprecated("stdexec::empty_env is now spelled stdexec::env<>")]] = env<>;
      |         ^~~~~~~~~
/Users/Nan/GSoC/hpx/libs/core/execution_base/include/hpx/execution_base/completion_signatures.hpp:537:54: warning: 'using stdexec::empty_env = struct stdexec::__env::env<>' is deprecated: stdexec::empty_env is now spelled stdexec::env<> [-Wdeprecated-declarations]
  537 |         typename Env = hpx::execution::experimental::empty_env>
      |                                                      ^~~~~~~~~
/Users/Nan/GSoC/hpx/build/_deps/stdexec-src/include/stdexec/__detail/__execution_fwd.hpp:102:9: note: declared here
  102 |   using empty_env [[deprecated("stdexec::empty_env is now spelled stdexec::env<>")]] = env<>;
      |         ^~~~~~~~~
gmake[3]: *** [libs/core/execution_base/CMakeFiles/hpx_execution_base.dir/build.make:79: libs/core/execution_base/CMakeFiles/hpx_execution_base.dir/src/agent_ref.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:111243: libs/core/execution_base/CMakeFiles/hpx_execution_base.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:54907: libs/core/algorithms/tests/unit/algorithms/CMakeFiles/uninitialized_relocate_sender_test.dir/rule] Error 2
gmake: *** [Makefile:6068: uninitialized_relocate_sender_test] Error 2
```

I suspect the issue stems from recent changes in [NVIDIA's upstream stdexec implementation](https://github.com/NVIDIA/stdexec).
We need to make some adjustments to ensure compatibility.

## Steps to Reproduce
1. Build HPX
```
cmake -S . -B build \
  -DCMAKE_INSTALL_PREFIX="$HOME/hpx_install" \
  -DCMAKE_BUILD_TYPE=Debug \
  -DHPX_WITH_EXAMPLES=OFF \
  -DHPX_WITH_TESTS=ON \
  -DHPX_WITH_CXX_STANDARD=20 \
  -DHPX_WITH_STDEXEC=ON \
  -DHPX_WITH_FETCH_ASIO=ON \
  -DCMAKE_C_COMPILER="$(brew --prefix)/bin/gcc-13" \
  -DCMAKE_CXX_COMPILER="$(brew --prefix)/bin/g++-13"
```

2. Build test
```
cmake --build build --target uninitialized_relocate_sender_test > build.log 2>&1
```

## Environment
OS Platform and Distribution: macOS 15.6.1

Build System: CMake 4.2.0

Hardware Architecture: Apple M4

### PR DESCRIPTION
**Pull request by sususu5**
Fixes #6842

## Proposed Changes

  - Removed `stdexec::dependent_domain` since it has been deleted in the upstream repo
  - Changed `stdexec::make_completion_signatures` to `exec::make_completion_signatures` to ensure consistency
  - Removed `stdexec::transform_env` since it has been deleted in the upstream repo
  - Added `query()` and `schedule()` functions to `thread_pool_policy_scheduler` to meet the requirement

## Any background context you want to provide?
[upstream repo](https://github.com/NVIDIA/stdexec)

## Checklist

Not all points below apply to all pull requests.

- [ ] I have added a new feature and have added tests to go along with it.
- [ ] I have fixed a bug and have added a regression test.
- [ ] I have added a test using random numbers; I have made sure it uses a seed, and that random numbers generated are valid inputs for the tests.

### CODE REVIEW

**Comment by hkaiser** [comment]
@isidorostsa Would you mind having a look?

File: libs/core/execution_base/include/hpx/execution_base/completion_signatures.hpp [hunk 1]
```diff
@@ -1806,5 +1807,7 @@ namespace hpx::execution::experimental {
     using make_completion_signatures =
         meta::type<detail::make_helper<Sender, Env, AddlSignatures,
             meta::func<SetValue>, meta::func1<SetError>, SendsStopped>>;
+#else
+    HPX_CXX_EXPORT using exec::make_completion_signatures;
```
Comment (isidorostsa) [inline libs/core/execution_base/include/hpx/execution_base/completion_signatures.hpp]: We don't appear to be using `make_completion_signatures` anywhere in the codebase, so we might as well avoid this dependency on `exec`

File: libs/core/executors/include/hpx/executors/thread_pool_scheduler.hpp [hunk 2]
```diff
@@ -355,6 +369,11 @@ namespace hpx::execution::experimental {
             return {sched};
         }
 
+        constexpr sender<thread_pool_policy_scheduler> schedule() const
+        {
+            return {*this};
+        }
+
```
Comment (isidorostsa) [inline libs/core/executors/include/hpx/executors/thread_pool_scheduler.hpp:376]: Looks good!

**Review by isidorostsa — COMMENTED** [review]
Hey David, thank you for your PR!

The completions you added in the thread pool scheduler make sense.

Also, good job spotting the removed stuff :)

File: libs/core/execution_base/include/hpx/execution_base/completion_signatures.hpp (hunk 1 above)
Comment (sususu5) [reply libs/core/execution_base/include/hpx/execution_base/completion_signatures.hpp]: Thank you so much! This part has been removed, shall I make a squash to the commits now or wait for the ci to be fixed. I suspect the failure is not generated from the codebase?

File: libs/core/executors/include/hpx/executors/thread_pool_scheduler.hpp (hunk 2 above)
Comment (isidorostsa) [reply libs/core/executors/include/hpx/executors/thread_pool_scheduler.hpp:376]: Do you think you should also add a non-const overload?

File: libs/core/executors/include/hpx/executors/thread_pool_scheduler.hpp [hunk 3]
```diff
@@ -298,6 +298,20 @@ namespace hpx::execution::experimental {
...
+                // clang-format off
+                template <typename CPO,
+                    HPX_CONCEPT_REQUIRES_(
+                        meta::value<meta::one_of<
+                            CPO, set_value_t, set_stopped_t>>
+                    )>
+                // clang-format on
+                constexpr auto query(
+                    hpx::execution::experimental::get_completion_scheduler_t<
```
Comment (isidorostsa) [inline libs/core/executors/include/hpx/executors/thread_pool_scheduler.hpp:310]: Nice spotting this too!

Comment (sususu5) [reply libs/core/executors/include/hpx/executors/thread_pool_scheduler.hpp:310]: I think both the `query()` and `schedule()` functions should only have const versions because scheduler is designed as a lightweight handle and these operations shouldn't change the states of the internal scheduler.

Comment (isidorostsa) [reply libs/core/executors/include/hpx/executors/thread_pool_scheduler.hpp:310]: Huh, I didn't know that, but it makes sense.

**Comment by isidorostsa** [comment]
This pool request is good to go, @sususu5 I'll ping you once CI is fixed so you can rebase and then we will be good to merge.

**Comment by sususu5** [comment]
> This pool request is good to go, @sususu5 I'll ping you once CI is fixed so you can rebase and then we will be good to merge.

Thanks!

**Comment by hkaiser** [comment]
@sususu5 please try rebasing onto master. The CIs should be ok now.

**Comment by sususu5** [comment]
> @sususu5 please try rebasing onto master. The CIs should be ok now.

Thanks for the reminder. After checking again, there are still a few tests failing because the clang-tidy subprocess is being killed.

**Comment by hkaiser** [comment]
> > @sususu5 please try rebasing onto master. The CIs should be ok now.
> 
> Thanks for the reminder. After checking again, there are still a few tests failing because the clang-tidy subprocess is being killed.

Yes, CircleCI runs out of memory. Feel free to ignore those errors.
