### PR TITLE
Fixing gcc warning on 32bit platforms (integer truncation)

### LINKED ISSUE #4215: HPX 1.4.0rc1 does not link on s390x
## Expected Behavior

HPX should compile on s390x as hpx 1.3.0 compiled there.

## Actual Behavior

Linking error for 

```
.a ../lib/libhpx_resource_partitioner.a ../lib/libhpx_cache.a ../lib/libhpx_coroutines.a ../lib/libhpx_util.a ../lib/libhpx_memory.a ../lib/libhpx_hardware.a ../lib/libhpx_plugin.a ../lib/libhpx_program_options.a /usr/lib64/libboost_program_options.so ../lib/libhpx_algorithms.a ../lib/libhpx_statistics.a ../lib/libhpx_execution.a ../lib/libhpx_allocator_support.a /usr/lib64/libtcmalloc_minimal.so ../lib/libhpx_topology.a /usr/lib64/libhwloc.so ../lib/libhpx_iterator_support.a ../lib/libhpx_functional.a ../lib/libhpx_concurrency.a ../lib/libhpx_basic_execution.a ../lib/libhpx_serialization.a ../lib/libhpx_debugging.a ../lib/libhpx_errors.a ../lib/libhpx_datastructures.a ../lib/libhpx_format.a ../lib/libhpx_logging.a ../lib/libhpx_filesystem.a ../lib/libhpx_timing.a ../lib/libhpx_thread_support.a ../lib/libhpx_hashing.a ../lib/libhpx_concepts.a ../lib/libhpx_type_support.a ../lib/libhpx_concepts.a ../lib/libhpx_type_support.a ../lib/libhpx_assertion.a ../lib/libhpx_config.a /usr/lib64/libboost_system.so -lpthread ../lib/libhpx_preprocessor.a 
/usr/bin/ld: CMakeFiles/hpx.dir/runtime/threads/detail/scheduled_thread_pool.cpp.o: in function `hpx::threads::coroutines::detail::lx::swap_context(hpx::threads::coroutines::detail::lx::x86_linux_context_impl_base&, hpx::threads::coroutines::detail::lx::x86_linux_context_impl_base const&, hpx::threads::coroutines::detail::default_hint)':
/builddir/build/BUILD/hpx_1.4.0/libs/coroutines/include/hpx/coroutines/detail/context_linux_x86.hpp:531: undefined reference to `swapcontext_stack'
/usr/bin/ld: CMakeFiles/hpx.dir/runtime/threads/execution_agent.cpp.o: in function `hpx::threads::coroutines::detail::lx::swap_context(hpx::threads::coroutines::detail::lx::x86_linux_context_impl_base&, hpx::threads::coroutines::detail::lx::x86_linux_context_impl_base const&, hpx::threads::coroutines::detail::yield_hint)':
/builddir/build/BUILD/hpx_1.4.0/libs/coroutines/include/hpx/coroutines/detail/context_linux_x86.hpp:542: undefined reference to `swapcontext_stack'
/usr/bin/ld: /builddir/build/BUILD/hpx_1.4.0/libs/coroutines/include/hpx/coroutines/detail/context_linux_x86.hpp:542: undefined reference to `swapcontext_stack'
/usr/bin/ld: ../lib/libhpx_coroutines.a(context_base.cpp.o): in function `hpx::threads::coroutines::detail::lx::swap_context(hpx::threads::coroutines::detail::lx::x86_linux_context_impl_base&, hpx::threads::coroutines::detail::lx::x86_linux_context_impl_base const&, hpx::threads::coroutines::detail::default_hint)':
/builddir/build/BUILD/hpx_1.4.0/libs/coroutines/include/hpx/coroutines/detail/context_linux_x86.hpp:531: undefined reference to `swapcontext_stack'
/usr/bin/ld: /builddir/build/BUILD/hpx_1.4.0/libs/coroutines/include/hpx/coroutines/detail/context_linux_x86.hpp:531: undefined reference to `swapcontext_stack'
/usr/bin/ld: ../lib/libhpx_coroutines.a(context_base.cpp.o):/builddir/build/BUILD/hpx_1.4.0/libs/coroutines/include/hpx/coroutines/detail/context_linux_x86.hpp:531: more undefined references to `swapcontext_stack' follow
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/hpx.dir/build.make:2478: lib/libhpx.so.1.4.0] Error 1
make[2]: Leaving directory '/builddir/build/BUILD/hpx_1.4.0/serial'
make[1]: *** [CMakeFiles/Makefile2:40314: src/CMakeFiles/hpx.dir/all] Error 2
make: *** [Makefile:144: all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.pqNZR6 (%build)
RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.pqNZR6 (%build)
Child return code was: 1
EXCEPTION: [Error()]
```

## Steps to Reproduce the Problem

Build HPX with on s390x, please look at the error log on [Fedora's build system](https://koji.fedoraproject.org/koji/getfile?taskID=38997711&volume=DEFAULT&name=build.log&offset=-4000) for more details.

## Specifications

... Please describe your environment

  - HPX Version: 1.4.1-rc1
  - Platform (compiler, OS): Fedora rawhide

### PR DESCRIPTION
**Pull request by hkaiser**
- flyby: move hpx_option to before first usage of the option value
- also fixes a misspelled pp constant

Fixes 32bit rpm builds, @msimberg I think this should be part of the V1.4 release

Fixes #4215

### CODE REVIEW

File: libs/hashing/include/hpx/hashing/fibhash.hpp [hunk 1]
```diff
@@ -29,18 +31,19 @@ namespace hpx { namespace util {
         template <std::size_t N>
         struct hash_helper
         {
-            HPX_STATIC_CONSTEXPR std::size_t log2 =
+            HPX_STATIC_CONSTEXPR std::uint64_t log2 =
```
Comment (msimberg) [inline libs/hashing/include/hpx/hashing/fibhash.hpp]: This needs `cstdint`. Should the template parameter be `uint64_t` too?

Comment (hkaiser) [reply libs/hashing/include/hpx/hashing/fibhash.hpp]: Right, most probably.

Comment (hkaiser) [reply libs/hashing/include/hpx/hashing/fibhash.hpp]: Done.

**Comment by hkaiser** [comment]
The failure is caused by the current state of affairs wrt APEX.
