### PR TITLE
Changing HPX_GCC_VERSION check from 70000 to 70300

### LINKED ISSUE #4220: HPX won't compile - error building resource_partitioner
## Expected Behavior

... Please describe the behavior you would have expected.

## Actual Behavior

The build is failing when compiling the resource_partitioner:
http://omega.nic.uoregon.edu:8020/#/builders/5/builds/38/steps/7/logs/stdio

## Steps to Reproduce the Problem

... Please be as specific as possible while describing how to reproduce your problem.

  1.  `cmake -DCMAKE_CXX_COMPILER=/packages/gcc/7.1/bin/g++ -DCMAKE_C_COMPILER=/packages/gcc/7.1/bin/gcc -DCMAKE_BUILD_TYPE=Debug -DBOOST_ROOT=/usr/local/packages/boost/1.65.0-gcc7 -DTCMALLOC_ROOT=/usr/local/packages/gperftools/git-gcc7 -DHPX_WITH_MALLOC=tcmalloc -DHWLOC_ROOT= -DCMAKE_INSTALL_PREFIX=. -DHPX_WITH_THREAD_IDLE_RATES=ON -DHPX_WITH_PARCELPORT_MPI=ON -DHPX_WITH_PARCEL_COALESCING=OFF -DHPX_WITH_TOOLS=OFF -DHPX_WITH_TESTS=ON -DHPX_WITH_EXAMPLES=OFF -DHPX_WITH_THREAD_MANAGER_IDLE_BACKOFF=OFF -DHPX_WITH_APEX=TRUE -DAPEX_WITH_ACTIVEHARMONY=TRUE -DACTIVEHARMONY_ROOT=/usr/local/packages/activeharmony/4.6.0-gcc -DAPEX_WITH_OTF2=TRUE -DOTF2_ROOT=/usr/local/packages/otf2-2.1 -DAPEX_WITH_PAPI=TRUE -DPAPI_ROOT=/usr/local/packages/papi/papi-knl/5.5.0/ -DHPX_WITH_APEX_NO_UPDATE=FALSE -DHPX_WITH_APEX_TAG=develop -DHPX_WITH_MAX_CPU_COUNT=72 /var/lib/buildbot/slaves/phylanx/x86_64-gcc7-debug/build/tools/buildbot/src/hpx`

  1. make
  1.

## Specifications

... Please describe your environment

  - HPX Version: current master
  - Platform (compiler, OS):  x86_64 linux, gcc 7.3

### PR DESCRIPTION
**Pull request by khuck**
Fixes #4220

## Proposed Changes

  -  Change 7 locations of 70000 to 70300
  -
  -

### CODE REVIEW

File: hpx/runtime/threads/thread_data.hpp [hunk 1]
```diff
@@ -243,7 +243,7 @@ namespace hpx { namespace threads {
 
     public:
         /// Return the id of the component this thread is running in
-#if defined(HPX_GCC_VERSION) && (HPX_GCC_VERSION >= 70000)
+#if defined(HPX_GCC_VERSION) && (HPX_GCC_VERSION >= 70300)
```
Comment (hkaiser) [inline hpx/runtime/threads/thread_data.hpp]: This disables constexpr for anything but gcc > V7.3, is that intended?

Comment (msimberg) [reply hpx/runtime/threads/thread_data.hpp]: Very good catch... not at all intended. @khuck I can push something on Monday if you'd like, unless you get to it first.
