### PR TITLE
Dispatching unhandled exceptions to outer user code

### LINKED ISSUE #582: Make exception thrown from HPX threads available from hpx::init
Unhandled exceptions thrown from HPX threads (those bubbling up into the thread manager) should be marshalled to the invocation site of `hpx::init()` and rethrown there.

### PR DESCRIPTION
**Pull request by hkaiser**
This resolves #582: Make exception thrown from HPX threads available from hpx::init

### CODE REVIEW

File: plugins/parcelport/mpi/parcelport_mpi.cpp [hunk 1]
```diff
@@ -272,16 +272,15 @@ namespace hpx { namespace parcelset { namespace policies { namespace mpi
...
-                            boost::lexical_cast<std::string>(ec.value())+ ")");
-                }
-                catch (hpx::exception const& e) {
-                    hpx::detail::report_exception_and_terminate(e);
-                }
-                return;
+                            boost::lexical_cast<std::string>(ec.value()) +
+                            ")" + parcelset::dump_parcel(p));
+
+                hpx::report_error(exception);
```
Comment (sithhell) [inline plugins/parcelport/mpi/parcelport_mpi.cpp]: Is the parcelport the only place where we have those constructs? I am pretty sure I just copy and pasted that from somewhere else.

**Comment by sithhell** [comment]
LGTM.

File: plugins/parcelport/mpi/parcelport_mpi.cpp (hunk 1 above)
Comment (hkaiser) [inline plugins/parcelport/mpi/parcelport_mpi.cpp]: One more other place was using this, I changed that as well.
