### PR TITLE
Changing default bind mode to balanced

### LINKED ISSUE #2015: Change default bind-mode to balanced
The current default for binding threads to cores is `--hpx:bind=compact`. This can lead to unexpected results on systems which have hyper-threading enabled. Changing the default to `--hpx:bind=balanced` would solve this while not changing things for non-hyper-threaded systems.

### PR DESCRIPTION
**Pull request by sithhell**
This fixes #2015

### CODE REVIEW

File: src/util/command_line_handling.cpp [hunk 1]
```diff
@@ -679,7 +679,7 @@ namespace hpx { namespace util
         affinity_domain_ = detail::handle_affinity(cfgmap, vm, "pu");
         ini_config += "hpx.affinity=" + affinity_domain_;
 
-        affinity_bind_ = detail::handle_affinity_bind(cfgmap, vm, "");
+        affinity_bind_ = detail::handle_affinity_bind(cfgmap, vm, "balanced");
         if (!affinity_bind_.empty())
```
Comment (biddisco) [inline src/util/command_line_handling.cpp]: Does the empty check still have a purpose since you've set a balanced default?

Comment (sithhell) [inline src/util/command_line_handling.cpp]: On 05/25/2016 11:41 AM, John Biddiscombe wrote:
> In src/util/command_line_handling.cpp
> <https://github.com/STEllAR-GROUP/hpx/pull/2180#discussion_r64543813>:
>
>> @@ -679,7 +679,7 @@ namespace hpx { namespace util
>>          affinity_domain_ = detail::handle_affinity(cfgmap, vm, "pu");
>>          ini_config += "hpx.affinity=" + affinity_domain_;
>>
>> -        affinity_bind_ = detail::handle_affinity_bind(cfgmap, vm, "");
>> +        affinity_bind_ = detail::handle_affinity_bind(cfgmap, vm, "balanced");
>>          if (!affinity_bind_.empty())
>
> Does the empty check still have a purpose since you've set a balanced
> default?

Good catch!
