### PR TITLE
Removing use of get_temporary_buffer and return_temporary_buffer

### LINKED ISSUE #4971: Parallel sort fails to compile with C++20
## Expected Behavior

Successfully compile a program that uses parallel sort

## Actual Behavior

A bunch of compile errors:
* 'return_temporary_buffer': is not a member of 'std'
* 'get_temporary_buffer': is not a member of 'std'
(algorithms/detail/spin_sort.hpp, algorithms/detail/parallel_stable_sort.hpp)

These functions are deprecated as of C++17 and removed in C++20.

## Specifications

  - HPX Version: 1.5.0
  - Platform (compiler, OS): MSVC 2019, Windows 10

### PR DESCRIPTION
**Pull request by hkaiser**
- these functions have been deprecated in C++17 and removed in C++20

Fixes #4971

### CODE REVIEW

File: libs/parallelism/algorithms/include/hpx/parallel/algorithms/detail/parallel_stable_sort.hpp [hunk 1]
```diff
@@ -101,11 +102,10 @@ namespace hpx { namespace parallel { inline namespace v1 { namespace detail {
                 return last;
             }
 
-            ptr = std::get_temporary_buffer<value_type>(nptr).first;
-            if (ptr == nullptr)
-            {
-                throw std::bad_alloc();
-            }
```
Comment (msimberg) [inline libs/parallelism/algorithms/include/hpx/parallel/algorithms/detail/parallel_stable_sort.hpp:108]: I suppose the `nullptr` check could stay?

**Review by msimberg — CHANGES_REQUESTED** [review]
Looks good to me besides the one comment. Thanks @hkaiser!

**Review by msimberg — APPROVED** [review]
