### PR TITLE
Convert enum message_buffer_append_state to enum class

### LINKED ISSUE #4702: Prefer enum class over unscoped enums
We should gradually move all unscoped enums to enum classes.

Some of those listed below could possibly be hidden in some detail namespace...

- [x] `thread_state_enum`
- [x] `thread_state_ex_enum`
- [x] `thread_stacksize`
- [x] `thread_priority`
- [x] `scheduler_mode` (#5809)
- [x] `scheduler_state` (#5809)
- [x] `component_enum_type`
- [x] `id_type::management_type` (#5817)
- [x] `cache::statistics::method` (#5816)
- [x] `commandline_error_mode`
- [x] `hpx::error`
- [x] `hpx::throwmode` (#5820)
- [x] `future_state`
- [x] `performance_counters::counter_type` (#5850)
- [x] `performance_counters::counter_status`
- [x] `performance_counters::discover_counters_mode`
- [x] `agas::service_mode`
- [x] `serialization::archive_flags`
- [x] `serialization::chunk_type`
- [x] `util::exception_type`
- [ ] `hpx_hwloc_membind_policy`
- [x] `message_buffer_append_state` (parcel coalescing) (#6923)
- [x] `distribution_type` (affinity)
- [x] `deque_status_type` (boost lockfree deque)
- [x] `context_state`, `context_exit_state`, `context_exit_status` (coroutines)
- [x] `logging_destination` (logging)
- [x] `partitioner_mode`

… there are more, please add to this list, if needed.

### PR DESCRIPTION
**Pull request by GitMasterJatin**
Convert message_buffer_append_state to enum class

Fixes #4702

## Proposed Changes

- Converted `message_buffer_append_state` from unscoped enum to `enum class` in the parcel coalescing plugin
- Added deprecated unscoped aliases for backward compatibility using `HPX_DEPRECATED_V(1, 10, ...)` 
- Updated all usage sites in `coalescing_message_handler.cpp` to use scoped enum syntax with fully qualified names

## Any background context you want to provide?

Issue #4702 tracks the gradual migration of all unscoped enums to enum classes throughout the HPX codebase. After a systematic review of the checklist, I found that most enums listed have already been converted. The `message_buffer_append_state` enum was the last remaining unscoped enum that needed conversion.

The conversion follows the established HPX pattern:
1. Change `enum` to `enum class`
2. Add `HPX_DEPRECATED_V` aliases as static constexpr members for backward compatibility
3. Update all usage sites to use the scoped syntax (e.g., `message_buffer_append_state::normal`)

This maintains backward compatibility while encouraging migration to type-safe enumerations.

**Files modified:**
- `components/parcel_plugins/coalescing/include/hpx/parcel_coalescing/message_buffer.hpp` (enum declaration and `append()` method)
- `components/parcel_plugins/coalescing/src/coalescing_message_handler.cpp` (switch-case statements)

## Checklist

Not all points below apply to all pull requests.

- [ ] I have added a new feature and have added tests to go along with it.
- [ ] I have fixed a bug and have added a regression test.
- [ ] I have added a test using random numbers; I have made sure it uses a seed, and that random numbers generated are valid inputs for the tests.

### CODE REVIEW

File: components/parcel_plugins/coalescing/include/hpx/parcel_coalescing/message_buffer.hpp [hunk 1]
```diff
@@ -25,14 +25,37 @@ namespace hpx::plugins::parcel::detail {
     class message_buffer
     {
     public:
-        enum message_buffer_append_state
+        enum class message_buffer_append_state
```
Comment (hkaiser) [inline components/parcel_plugins/coalescing/include/hpx/parcel_coalescing/message_buffer.hpp]: While we're at it, I think we can reduce the size of the enum as well:
```suggestion
        enum class message_buffer_append_state : std::uint8_t
```

File: components/parcel_plugins/coalescing/include/hpx/parcel_coalescing/message_buffer.hpp [hunk 2]
```diff
@@ -25,14 +25,37 @@ namespace hpx::plugins::parcel::detail {
...
             buffer_now_full = 2,
             singleton_buffer = 3
         };
 
+#define HPX_MESSAGE_BUFFER_APPEND_STATE_UNSCOPED_ENUM_DEPRECATION_MSG         \
+    "The unscoped message_buffer_append_state names are deprecated. "        \
+    "Please use message_buffer_append_state::<value> instead."
+
+        HPX_DEPRECATED_V(
+            1, 10, HPX_MESSAGE_BUFFER_APPEND_STATE_UNSCOPED_ENUM_DEPRECATION_MSG)
```
Comment (hkaiser) [inline components/parcel_plugins/coalescing/include/hpx/parcel_coalescing/message_buffer.hpp]: These will be deprecated starting V2.0 (which is the next version of HPX to be released):
```suggestion
            2, 0, HPX_MESSAGE_BUFFER_APPEND_STATE_UNSCOPED_ENUM_DEPRECATION_MSG)
```

**Review by hkaiser — COMMENTED** [review]
Thank you for working on this!

File: components/parcel_plugins/coalescing/include/hpx/parcel_coalescing/message_buffer.hpp [hunk 3]
```diff
@@ -25,14 +25,37 @@ namespace hpx::plugins::parcel::detail {
...
+#define HPX_MESSAGE_BUFFER_APPEND_STATE_UNSCOPED_ENUM_DEPRECATION_MSG         \
+    "The unscoped message_buffer_append_state names are deprecated. "        \
+    "Please use message_buffer_append_state::<value> instead."
+
+        HPX_DEPRECATED_V(
+            2, 0, HPX_MESSAGE_BUFFER_APPEND_STATE_UNSCOPED_ENUM_DEPRECATION_MSG)
+        static constexpr message_buffer_append_state normal =
+            message_buffer_append_state::normal;
+        HPX_DEPRECATED_V(
+            1, 10, HPX_MESSAGE_BUFFER_APPEND_STATE_UNSCOPED_ENUM_DEPRECATION_MSG)
```
Comment (hkaiser) [inline components/parcel_plugins/coalescing/include/hpx/parcel_coalescing/message_buffer.hpp]: All the remaining deprecations need to be corrected as well

File: components/parcel_plugins/coalescing/include/hpx/parcel_coalescing/message_buffer.hpp [hunk 4]
```diff
@@ -25,14 +25,37 @@ namespace hpx::plugins::parcel::detail {
     class message_buffer
     {
     public:
-        enum message_buffer_append_state
+        enum class message_buffer_append_state : std::uint8_t
```
Comment (hkaiser) [inline components/parcel_plugins/coalescing/include/hpx/parcel_coalescing/message_buffer.hpp:29]: Most likely, inspect will now complain about a missing `#include <cstdint>`

File: components/parcel_plugins/coalescing/include/hpx/parcel_coalescing/message_buffer.hpp [hunk 5]
```diff
@@ -25,14 +26,37 @@ namespace hpx::plugins::parcel::detail {
...
             first_message = 1,
             buffer_now_full = 2,
             singleton_buffer = 3
         };
 
+#define HPX_MESSAGE_BUFFER_APPEND_STATE_UNSCOPED_ENUM_DEPRECATION_MSG          \
+    "The unscoped message_buffer_append_state names are deprecated. "          \
+    "Please use message_buffer_append_state::<value> instead."
+
+        HPX_DEPRECATED_V(1, 10,
```
Comment (hkaiser) [inline components/parcel_plugins/coalescing/include/hpx/parcel_coalescing/message_buffer.hpp]: As said before, the deprecation starts at V2.0, please adjust all of the below accordingly:
```suggestion
        HPX_DEPRECATED_V(2, 0,
```

**Comment by hkaiser** [comment]
@GitMasterJatin What are your plans with this PR? Would you have the time to address the remaining issues?

**Comment by GitMasterJatin** [comment]
> @GitMasterJatin What are your plans with this PR? Would you have the time to address the remaining issues?

Yes, working on it, will push changes in some time.

File: components/parcel_plugins/coalescing/include/hpx/parcel_coalescing/message_buffer.hpp (hunk 5 above)
Comment (GitMasterJatin) [reply components/parcel_plugins/coalescing/include/hpx/parcel_coalescing/message_buffer.hpp]: Done.

File: components/parcel_plugins/coalescing/include/hpx/parcel_coalescing/message_buffer.hpp (hunk 3 above)
Comment (GitMasterJatin) [reply components/parcel_plugins/coalescing/include/hpx/parcel_coalescing/message_buffer.hpp]: Done.

File: components/parcel_plugins/coalescing/include/hpx/parcel_coalescing/message_buffer.hpp (hunk 2 above)
Comment (GitMasterJatin) [reply components/parcel_plugins/coalescing/include/hpx/parcel_coalescing/message_buffer.hpp]: Done

File: components/parcel_plugins/coalescing/include/hpx/parcel_coalescing/message_buffer.hpp (hunk 1 above)
Comment (GitMasterJatin) [reply components/parcel_plugins/coalescing/include/hpx/parcel_coalescing/message_buffer.hpp]: Done.

**Comment by GitMasterJatin** [comment]
> LGTM, thanks!

Thank you sir for the review
