### PR TITLE
Added random repeating numbers in tests and fixed sentinel tests for extrema algorithms

### LINKED ISSUE #6627: Extrema algorithms with repeated values
Extrema algorithms (min_element/max_element/minmax_element) have specific semantics in case of repeated values. The existing unit tests don't cover these, as they only use `random_iota` as the input range. In particular:

- `min_element` is required to return the first min value,
- `max_element` is required to return the first max value,
- `minmax_element` is required to return the first min value and the last max value.

Tests for these cases should be added, and the implementations adjusted as needed.

### PR DESCRIPTION
**Pull request by 0lem1of1**
Fixes #6627 

## Proposed Changes

  -Added random_repeat utility function to generate vectors with repeated/duplicate values for testing extrema algorithms (min_element, max_element, minmax_element)
  -Replaced random_iota with random_repeat in all extrema algorithm tests to properly test behavior with duplicate values
  -Modified sentinel tests in container_algorithms to use random_repeat with a unique sentinel value (101) placed at the desired position, ensuring sentinels work correctly with duplicate data

## Any background context you want to provide?

This PR addresses issue #6627 regarding testing extrema algorithms with repeated values.
The previous test data used random_iota which generates unique values, meaning the "first occurrence" behavior of min_element/max_element was never actually tested. By using random_repeat, we now generate data with duplicates (values 0-100 repeated across 10007 elements), which properly exercises the algorithm's requirement to return the first minimum/maximum element.
For sentinel tests in container_algorithms, we inject a unique sentinel value (101) at the desired position to prevent the sentinel from stopping prematurely when duplicate values exist in the data
Thanks to the authors of PR #6724 for initial direction
## Checklist

Not all points below apply to all pull requests.

- [x] I have added a new feature and have added tests to go along with it.
- [ ] I have fixed a bug and have added a regression test.
- [x] I have added a test using random numbers; I have made sure it uses a seed, and that random numbers generated are valid inputs for the tests.

### CODE REVIEW

File: libs/core/algorithms/tests/unit/algorithms/test_utils.hpp [hunk 1]
```diff
@@ -208,6 +208,33 @@ namespace test {
...
+        std::vector<T> c(size);
+        std::random_device rd;
+        std::mt19937 g(rd());
+        std::uniform_int_distribution<T> dist(0, max_value);
+        for (std::size_t i = 0; i < size; ++i)
+        {
+            c[i] = dist(g);
+        }
+        return c;
+    }
```
Comment (hkaiser) [inline libs/core/algorithms/tests/unit/algorithms/test_utils.hpp:223]: What is your rationale for providing two versions of the same functionality (one for sequences of `std::size_t` and one (identical) generic version? Wouldn't the generic version be sufficient?

File: libs/core/algorithms/tests/unit/container_algorithms/test_utils.hpp [hunk 2]
```diff
@@ -296,6 +296,34 @@ namespace test {
...
+        std::vector<T> c(size);
+        std::random_device rd;
+        std::mt19937 g(rd());
+        std::uniform_int_distribution<T> dist(0, max_value);
+        for (std::size_t i = 0; i < size; ++i)
+        {
+            c[i] = dist(g);
+        }
+        return c;
+    }
```
Comment (hkaiser) [inline libs/core/algorithms/tests/unit/container_algorithms/test_utils.hpp:311]: Same question here: why two identical versions of the new function `random_repeat`?

File: libs/core/algorithms/tests/unit/algorithms/test_utils.hpp (hunk 1 above)
Comment (0lem1of1) [reply libs/core/algorithms/tests/unit/algorithms/test_utils.hpp:223]: You're right that the generic version would be sufficient on its own. I followed the existing pattern from `random_iota` (which also has both a `std::size_t` specialization and a generic template version) for consistency. The non-template version serves as a convenience overload so callers don't need to explicitly specify `<std::size_t>` for the most common case.
That said, if you'd prefer I remove the `std::size_t` version and keep only the generic template, I'm happy to make that change.

File: libs/core/algorithms/tests/unit/container_algorithms/test_utils.hpp (hunk 2 above)
Comment (0lem1of1) [reply libs/core/algorithms/tests/unit/container_algorithms/test_utils.hpp:311]: same here , i tried to follow the existing pattern from `random_iota`

File: libs/core/algorithms/tests/unit/algorithms/test_utils.hpp (hunk 1 above)
Comment (hkaiser) [reply libs/core/algorithms/tests/unit/algorithms/test_utils.hpp:223]: Yes, let's remove the specialized version. FWIW, I don't think users need to specify the `std::size_t` even for the generic case, `T` will be deduced by the compiler.

Comment (0lem1of1) [reply libs/core/algorithms/tests/unit/algorithms/test_utils.hpp:223]: very well , ill make the changes
